application:
  type: "html"

deploy:
  deploymentName: demo-application
  fromDockerHost: "gcr.io"
  fromDockerRepo: "/cloudrun/hello"
  helmRepo: "https://raw.githubusercontent.com/its-software-services-devops/helm-cloudrun-app/main/"
  helmChartName: "helm-cloudrun-app"

  environments:
    - env: Development
      instance: Dev
      appNameSuffix: ""
      defaultTag: latest
      platform: CloudRun
      vaultKey: Dev
      deployPolicy: Always #MatchInstance
      project: its-artifact-commons
      region: asia-southeast1
      helmChartVersion: 1.1.0
      allowUnauthenHttp: true
      #tokenKeyID: SecretIdNonProd

      deployParams:
        - --set serviceName='webapp-demo'
        - --set containers[0].image='{{DOCKER_IMAGE_NAME}}:{{DOCKER_IMAGE_TAG}}'
        - --set-string containers[0].ports[0].containerPort='8080'
        - --set containers[0].resources.limits.cpu='1000m'
        - --set containers[0].resources.limits.memory='400Mi'

    - env: Production
      instance: Prod
      appNameSuffix: ""
      defaultTag: latest
      platform: CloudRun
      vaultKey: Prod
      deployPolicy: Always #Match
      project: its-artifact-commons
      region: asia-southeast1
      helmChartVersion: 1.1.0
      allowUnauthenHttp: true
      #tokenKeyID: SecretIdProd

      deployParams:
        - --set serviceName='webapp-demo'
        - --set containers[0].image='{{DOCKER_IMAGE_NAME}}:{{DOCKER_IMAGE_TAG}}'
        - --set containers[0].env[0].name='PORT'
        - --set containers[0].env[0].value='8080'
        - --set containers[0].ports[0].containerPort='8080'
        - --set containers[0].resources.limits.cpu='1000m'
        - --set containers[0].resources.limits.memory='400Mi'     
