---
controller:
  service:
    enabled: true
    type: ClusterIP
    annotations:
      cloud.google.com/neg: '{"ingress": true}'
      cloud.google.com/backend-config: '{"default": "nginx-hc-config"}'
