apiVersion: v1
kind: Service
metadata:
  name: nginx-ext
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app: default-http-backend
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 8080