apiVersion: v1
kind: Service
metadata:
  name: nginx-ext
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app: ingress-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s-ext
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: prometheus
    prometheus: k8s    
  ports:
  - name: http-web
    protocol: TCP
    port: 9090
    targetPort: web
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-k8s-ext
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus   
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-backend
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  rules:
    - host: nginx-backend.rke-demo.its-software-services.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: default-http-backend
                port:
                  number: 80
