---
exposes:
  domain: gcp-rke-demo.its-software-services.com
  issuer: lets-encrypt-issuer
  ingresses:
  - createCert: true
    name: grafana-syslog
    service:
      name: grafana-syslog
      port:
        number: 80

grafana:
  enabled: true
  fullnameOverride: grafana-syslog
  lokiQueryUrl: http://loki-syslog-query-frontend:3100
  image:
    tag: 7.5.7
  envRenderSecret:
    OKTA_CLIENT_ID: "will-change"
    OKTA_CLIENT_SECRET: "will-change"
    OKTA_TENANT_ID: "will-change"
  grafana.ini:
    server:
      root_url: https://grafana-syslog.gcp-rke-demo.its-software-services.com
    auth.okta:
      name: Okta
      enabled: true
      allow_sign_up: true
      client_id: ${OKTA_CLIENT_ID}
      client_secret: ${OKTA_CLIENT_SECRET}
      scopes: openid profile email groups
      auth_url: https://${OKTA_TENANT_ID}.okta.com/oauth2/v1/authorize
      token_url: https://${OKTA_TENANT_ID}.okta.com/oauth2/v1/token
      api_url: https://${OKTA_TENANT_ID}.okta.com/oauth2/v1/userinfo
      allowed_domains:
      allowed_groups: developer
      role_attribute_path: contains(groups[*], 'admin') && 'Admin' || contains(groups[*], 'developer') && 'Editor' || 'Viewer'

promtail:
  enabled: false
  customParams:
    #Loki gateway authen
    basicAuthUser: willchange111
    basicAuthPassword: willchangepwd2222
  config:
    lokiAddress: http://loki-syslog-gateway/loki/api/v1/push
  extraPorts: {}
  #  syslog:
  #    service:
  #      nodePort: 32001
  #    annotations:
  #      external-dns.alpha.kubernetes.io/hostname: promtail-syslog.gcp-rke-demo.its-software-services.com.
  #      external-dns.alpha.kubernetes.io/access: private

loki-distributed:
  enabled: true
  fullnameOverride: loki-syslog

  gateway:
    basicAuth:
      enabled: true
      username: willchange111
      password: willchangepwd2222

  customParams:
    backendStorageType: gcs
    gcsBucket: loki-syslog
    s3User: notused

  querier:
    extraEnv:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/key.json
    extraVolumes:
      - name: loki-access-gcs
        secret:
          secretName: loki-gcs-bucket-key
    extraVolumeMounts:
      - name: loki-access-gcs
        mountPath: /etc/secrets

  ingester:
    extraEnv:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/key.json
    extraVolumes:
      - name: loki-access-gcs
        secret:
          secretName: loki-gcs-bucket-key
    extraVolumeMounts:
      - name: loki-access-gcs
        mountPath: /etc/secrets

  compactor:
    enabled: true
    extraEnv:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/key.json
    extraVolumes:
      - name: loki-access-gcs
        secret:
          secretName: loki-gcs-bucket-key
    extraVolumeMounts:
      - name: loki-access-gcs
        mountPath: /etc/secrets
