fullnameOverride: vector-loki

rbac:
  enabled: true

serviceAccount:
  create: true

storage:
  mode: managedPersistentVolumeClaim
  managedPersistentVolumeClaim:
    size: 10Gi

extraContainersPorts:
  - containerPort: 9090 # Prometheus

service:
  ports:
    - name: http
      port: 9090 # Prometheus
      protocol: TCP
      targetPort: 9090

customConfig:
  data_dir: "/vector-data-dir" #Do not change this if you don't know the impact
  sources:
    kafka_syslog:
      type: kafka
      acknowledgements: null
      bootstrap_servers: kafka-log-bootstrap.gcp-rke-demo.its-software-services.com:31888
      group_id: syslog-to-loki
      topics:
        - kafka-syslog-topic

    internal_metrics:
      type: internal_metrics

  sinks:
    loki_syslog:
      type: loki
      inputs:
        - kafka_syslog
      endpoint: http://loki-syslog-gateway.loki-syslog.svc.cluster.local/loki/api/v1/push
      auth:
        strategy: basic
        user: willchange111
        password: willchangepwd2222
      labels: {}
      out_of_order_action: drop
      remove_timestamp: true
      encoding: {}

    prometheus_sink:
      type: prometheus_exporter
      inputs: ["internal_metrics"]
      address: 0.0.0.0:9090
