apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-log-broker
spec:
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"  
  kafka:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    version: 2.8.0
    replicas: 3
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false

      - name: tls
        port: 9093
        type: internal
        tls: true

      - name: np
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 31888
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-log-bootstrap.gcp-rke-demo.its-software-services.com.
              external-dns.alpha.kubernetes.io/access: private
          brokers:
          - broker: 0
            nodePort: 31990
            advertisedHost: kafka-log-broker-0.gcp-rke-demo.its-software-services.com
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-log-broker-0.gcp-rke-demo.its-software-services.com.
              external-dns.alpha.kubernetes.io/access: private
          - broker: 1
            nodePort: 31991
            advertisedHost: kafka-log-broker-1.gcp-rke-demo.its-software-services.com
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-log-broker-1.gcp-rke-demo.its-software-services.com.
              external-dns.alpha.kubernetes.io/access: private            
          - broker: 2
            nodePort: 31992
            advertisedHost: kafka-log-broker-2.gcp-rke-demo.its-software-services.com
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-log-broker-2.gcp-rke-demo.its-software-services.com.
              external-dns.alpha.kubernetes.io/access: private            
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  zookeeper:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}