global:
  resolve_timeout: 5m
  slack_api_url: '__SLACK_URL__'
route:
  receiver: 'slack-notifications'
  group_by: [ 'alertname' ]
  routes:
    - receiver: 'discard'
      continue: false
      match_re:
        alertname: ^.+ContainersDown$|^.+ContainerDown$ #This alert requires metric that available on OpenShift. 
    
    - receiver: 'discard'
      continue: false
      match_re:
        alertname: AvgRequestLatency #Finding the way to change treshold from 10 to another value. 

    - receiver: 'discard'
      continue: false
      match_re:
        alertname: ^NoMessageForTooLong$
        topic: ^__strimzi.+$

    - receiver: 'slack-notifications'
      continue: true
      match_re:
        alertname: .+
receivers:
  - name: 'discard'
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#etda-logs-monitor'
      send_resolved: true
      icon_url: https://avatars3.githubusercontent.com/u/3380462
      title: |-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
        {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
        {{" "}}(
        {{- with .CommonLabels.Remove .GroupLabels.Names }}
          {{- range $index, $label := .SortedPairs -}}
            {{ if $index }}, {{ end }}
            {{- $label.Name }}="{{ $label.Value -}}"
          {{- end }}
        {{- end -}}
          )
        {{- end }}
      text: |-
        {{ range .Alerts -}}
        *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
        {{ if .Annotations.description }}*Description:* {{ .Annotations.description }}{{ end }}
        {{ if .Annotations.message }}*Message:* {{ .Annotations.message }}{{ end }}
        {{ if .Annotations.summary }}*Summary:* {{ .Annotations.summary }}{{ end }}
        {{ if .Annotations.runbook_url }}*Runbook URL:* {{ .Annotations.runbook_url }}{{ end }}
        *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}
