apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
spec:
  route:
    receiver: 'slack-notifications'
    group_by: [ 'alertname' ]
    routes:
      - receiver: 'discard'
        match_re:
          alertname: CPUThrottlingHigh
          namespace: monitoring
      - receiver: 'discard'
        match_re:
          alertname: KubeControllerManagerDown|KubeSchedulerDown
  receivers:
    - name: 'discard'
    - name: 'slack-notifications'
      slackConfigs:
      - channel: '#etda-logs-monitor'
        apiURL: '__SLACK_URL__'
        sendResolved: true
        iconURL: https://avatars3.githubusercontent.com/u/3380462
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
          {{" "}}(
          {{- with .CommonLabels.Remove .GroupLabels.Names }}
            {{- range $index, $label := .SortedPairs -}}
              {{ if $index }}, {{ end }}
              {{- $label.Name }}="{{ $label.Value -}}"
            {{- end }}
          {{- end -}}
            )
          {{- end }}
        text: |-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          {{ if .Annotations.description }}*Description:* {{ .Annotations.description }}{{ end }}
          {{ if .Annotations.message }}*Message:* {{ .Annotations.message }}{{ end }}
          {{ if .Annotations.summary }}*Summary:* {{ .Annotations.summary }}{{ end }}
          *Runbook URL:* {{ .Annotations.runbook_url }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
