apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack  
spec:
  route:
    receiver: 'slack-notifications'
    groupBy: [ 'alertname' ]
    routes:
      - receiver: 'slack-notifications'
        continue: ture
        matchers:
          - name: alertname
            value: .+
            regex: true
      - receiver: 'slack-notifications'
        continue: ture
        matchers:
          - name: alertname
            value: NoMessageForTooLong
            regex: true            
  receivers:
    - name: 'slack-notifications'
      slackConfigs:
      - channel: '#etda-logs-monitor'
        apiURL:
          name: alertmanager-config-secret
          key: slackApiUrl
        sendResolved: true
        iconURL: https://avatars3.githubusercontent.com/u/3380462
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
          {{" "}}(
          {{- with .CommonLabels.Remove .GroupLabels.Names }}
            {{- range $index, $label := .SortedPairs -}}
              {{ if $index }}, {{ end }}
              {{- $label.Name }}="{{ $label.Value -}}"
            {{- end }}
          {{- end -}}
            )
          {{- end }}
        text: |-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          {{ if .Annotations.description }}*Description:* {{ .Annotations.description }}{{ end }}
          {{ if .Annotations.message }}*Message:* {{ .Annotations.message }}{{ end }}
          {{ if .Annotations.summary }}*Summary:* {{ .Annotations.summary }}{{ end }}
          *Runbook URL:* {{ .Annotations.runbook_url }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: alertmanager-config-secret
data:
  slackApiUrl: '__SLACK_URL__'
