fullnameOverride: grafana-platform
image:
  tag: 7.5.7
envRenderSecret:
  OKTA_CLIENT_ID: "will-change"
  OKTA_CLIENT_SECRET: "will-change"
  OKTA_TENANT_ID: "will-change"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus-Platform
      type: prometheus
      access: Server
      url: http://kube-prometheus-stack-prometheus.platform-monitoring.svc.cluster.local:9090
      #skip tls
    - name: Loki-SysLog
      type: Loki
      access: Server
      url: http://loki-syslog-query-frontend.loki-syslog.svc.cluster.local:3100
      #skip tls


dashboardProviders: {}
dashboardsConfigMaps: {}

grafana.ini:
  server:
    root_url: https://grafana-platform.gcp-rke-demo.its-software-services.com
  auth.okta:
    name: Okta
    enabled: true
    allow_sign_up: true
    client_id: ${OKTA_CLIENT_ID}
    client_secret: ${OKTA_CLIENT_SECRET}
    scopes: openid profile email groups
    auth_url: https://${OKTA_TENANT_ID}.okta.com/oauth2/v1/authorize
    token_url: https://${OKTA_TENANT_ID}.okta.com/oauth2/v1/token
    api_url: https://${OKTA_TENANT_ID}.okta.com/oauth2/v1/userinfo
    allowed_domains:
    allowed_groups: developer
    role_attribute_path: 'Admin'