apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-cluster-operator-metrics
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  namespaceSelector:
    matchNames:
      - kafka-operator
  podMetricsEndpoints:
  - path: /metrics
    port: http
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-entity-operator-metrics
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: entity-operator
  namespaceSelector:
    matchNames:
      - kafka-log-broker
  podMetricsEndpoints:
  - path: /metrics
    port: healthcheck
