apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-cluster-operator-metrics
  labels:
    release: platform-monitor
spec:
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  namespaceSelector:
    matchNames:
      - kafka-operator
  podMetricsEndpoints:
  - path: /metrics
    port: http
