---
prometheus:
  prometheusSpec:
    retention: 14d
    retentionSize: 70GB
    storageSpec:
    ## Using PersistentVolumeClaim
    ##
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 75Gi

##### Excluded portions #####
kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false

kubeStateMetrics:
  enabled: false

kubeDns:
  enabled: false

coreDns:
  enabled: false

kubeControllerManager:
  enabled: false

kubelet:
  enabled: false

kubeApiServer:
  enabled: false

grafana:
  enabled: false

defaultRules:
  create: false

nodeExporter:
  enabled: false

prometheusOperator:
  enabled: false