---
#prometheus:

##### Excluded portions #####
kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false

kubeStateMetrics:
  enabled: false

kubeDns:
  enabled: false

coreDns:
  enabled: false

kubeControllerManager:
  enabled: false

kubelet:
  enabled: false

kubeApiServer:
  enabled: false

grafana:
  enabled: false

defaultRules:
  create: false

nodeExporter:
  enabled: false

prometheusOperator:
  enabled: false