fullnameOverride: gcp-cloud-dns
provider: google

domainFilters:
  - gcp-rke-demo.its-software-services.com

google:
  project: its-artifact-commons
  serviceAccountSecret: gcp-cloud-dns-key
  serviceAccountSecretKey: key.json

txtOwnerId: gcp-rke-demo-ext-dns