spec:
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitoring: "true"
  retention: 5d
  retentionSize: 49GB      
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
