alertmanager:
  generic:
    namespace: monitoring
    enabled: true
    createSecret: true
    config:
      alertNoti:
        slackUrl: ''
        channel: '#yru-openedx-monitor'
        discardRules:
          - alertname: 'CPUThrottlingHigh'
            namespace: 'monitoring'            
          - alertname: 'KubeControllerManagerDown|KubeSchedulerDown'

prometheus: {}

alertRules: {}
