---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-k8s-ing
  namespace: monitoring
  annotations: {}
spec:
  tls:
    - hosts:
      - prometheus-k8s.yru-openedx-prod.its-software-services.com
      secretName: prometheus-k8s-cert
  rules:
    - host: prometheus-k8s.yru-openedx-prod.its-software-services.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-k8s
                port:
                  number: 9090
