global:
  domain: its-rke-demo.its-software-services.com
  certNamespace: ingress-nginx
  issuerNamespace: cert-manager
  #envSuffix: ''
  letsEncryptEnv: prod
  dns01:
    cloudDNS:
      project: its-artifact-commons
      serviceAccountSecretRef:
        name: gcp-cloud-dns-account-key
        key: service-account.json
issuers:
  - name: lets-encrypt-issuer
    email: pjame.fb@gmail.com

certificates:
  - name: default-certs
    issuerRef: lets-encrypt-issuer
