alertmanager:
  generic:
    namespace: monitoring
    enabled: true
    createSecret: true
    config:
      alertNoti:
        slackUrl: 'https://hooks.slack.com/services/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'
        channel: '#rke-demo'
        discardRules:
          - alertname: 'CPUThrottlingHigh'
            namespace: 'monitoring'            
          - alertname: 'KubeControllerManagerDown|KubeSchedulerDown'

prometheus: {}

alertRules: {}
