apiVersion: v1
kind: Service
metadata:
  name: nginx-neg
  namespace: ingress-nginx
  annotations:
    cloud.google.com/neg: '{"ingress": true}'  
spec:
  type: ClusterIP
  selector:
    app: ingress-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
